#!/bin/bash
# Demo: Generate videos using FFT-filtered flows

echo "==================================================================="
echo "FFT Motion Transfer - Hand vs Body Motion Control Demo"
echo "==================================================================="
echo ""
echo "This script demonstrates using FFT-filtered flows for video generation"
echo ""

# Step 1: Generate with original flow (baseline)
echo "Step 1: Generate with ORIGINAL flow (baseline)..."
echo "Command: python make_warped_noise.py ..."
echo ""

# Step 2: Generate with hands-emphasized flow
echo "Step 2: Generate with HANDS EMPHASIZED flow..."
echo "  - Removed slow body drift (Band 0)"
echo "  - Reduced body sway (Band 1)"
echo "  - Amplified fast hand motion (Bands 2-3)"
echo ""
echo "To use the filtered flow:"
echo "  1. Replace flows_dxdy.npy with test_hands_emphasized.npy"
echo "  2. Run cut_and_drag_inference.py"
echo ""

# Step 3: Generate with ultra-smooth flow
echo "Step 3: Generate with ULTRA SMOOTH flow..."
echo "  - Kept only slow motion"
echo "  - Removed all fast gestures"
echo ""

# Step 4: Compare results
echo "==================================================================="
echo "Quick Test Command:"
echo "==================================================================="
echo ""
echo "# Option 1: Use existing pipeline with filtered flow"
echo "cp test_hands_emphasized.npy my_warped_noise/flows_dxdy_original_backup.npy"
echo "cp test_hands_emphasized.npy my_warped_noise/flows_dxdy.npy"
echo "# Then re-run make_warped_noise.py or cut_and_drag_inference.py"
echo ""
echo "# Option 2: Create new warped noise from filtered flow"
echo "python -c \""
echo "import numpy as np"
echo "import sys"
echo "sys.path.append('.')"
echo "from CommonSource import noise_warp as nw"
echo ""
echo "# Load filtered flow"
echo "filtered_flow = np.load('test_hands_emphasized.npy')"
echo "print(f'Filtered flow shape: {filtered_flow.shape}')"
echo ""
echo "# TODO: Apply warping with filtered flow"
echo "# This requires integrating with the noise_warp module"
echo "\""
echo ""
echo "==================================================================="
echo "Analysis Complete!"
echo "==================================================================="
echo "Saved flows:"
echo "  - test_hands_emphasized.npy  (fast motion emphasized)"
echo "  - test_ultra_smooth.npy      (smooth, slow motion only)"
echo "  - test_extreme_hands.npy     (extreme fast emphasis)"
echo ""
echo "To visualize the difference:"
echo "  python -c 'import numpy as np; print(\"Original:\", np.load(\"fft_filtered/raw_flows.npy\")[:,0].mean()); print(\"Hands:\", np.load(\"test_hands_emphasized.npy\")[:,0].mean())'"
echo ""
